import http from 'http';

const PORT = process.env.PORT || 10000;

const INBOUND_GREETING = process.env.INBOUND_GREETING || 'Hoi, met Tessa van DES.';
const ELEVEN_API_KEY = process.env.ELEVENLABS_API_KEY;
const ELEVEN_VOICE_ID = process.env.ELEVENLABS_VOICE_ID;
const ELEVEN_MODEL = process.env.ELEVENLABS_MODEL || 'eleven_multilingual_v2';

// In-memory cache (simpel, 1 bestand). Voor inbound greeting is dit genoeg.
let cachedMp3 = null;
let cachedText = null;
let cachedAt = 0;

const server = http.createServer(async (req, res) => {
  // health
  if (req.method === 'GET' && req.url === '/health') {
    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ ok: true, ts: new Date().toISOString() }));
    return;
  }

  // serve generated audio
  if (req.method === 'GET' && req.url === '/audio.mp3') {
    if (!cachedMp3) {
      res.writeHead(404, { 'Content-Type': 'text/plain' });
      res.end('No audio cached');
      return;
    }
    res.writeHead(200, {
      'Content-Type': 'audio/mpeg',
      'Cache-Control': 'no-store'
    });
    res.end(cachedMp3);
    return;
  }

  // Twilio Voice webhook (inbound) -> TwiML
  if (req.method === 'POST' && req.url === '/twiml') {
    console.log(`[${new Date().toISOString()}] TwiML hit /twiml`);

    // Fallback: als Eleven niet geconfigureerd is, altijd Say
    if (!ELEVEN_API_KEY || !ELEVEN_VOICE_ID) {
      const twiml = `<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Say language="nl-NL">${escapeXml(INBOUND_GREETING)}</Say>
</Response>`;
      res.writeHead(200, { 'Content-Type': 'text/xml' });
      res.end(twiml);
      console.log(`[${new Date().toISOString()}] Eleven missing -> <Say> fallback`);
      return;
    }

    // Cache: als greeting tekst gelijk is en cache < 1 uur oud, hergebruik
    const now = Date.now();
    const cacheValid = cachedMp3 && cachedText === INBOUND_GREETING && now - cachedAt < 60 * 60 * 1000;

    if (!cacheValid) {
      try {
        const t0 = Date.now();
        cachedMp3 = await synthesizeElevenMp3(INBOUND_GREETING);
        cachedText = INBOUND_GREETING;
        cachedAt = Date.now();
        console.log(
          `[${new Date().toISOString()}] ✅ Eleven greeting generated bytes=${cachedMp3.length} ms=${Date.now() - t0}`
        );
      } catch (e) {
        console.error(`[${new Date().toISOString()}] ❌ Eleven failed, fallback <Say>:`, e.message);
        const twiml = `<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Say language="nl-NL">${escapeXml(INBOUND_GREETING)}</Say>
</Response>`;
        res.writeHead(200, { 'Content-Type': 'text/xml' });
        res.end(twiml);
        return;
      }
    } else {
      console.log(`[${new Date().toISOString()}] ♻️ Using cached Eleven mp3`);
    }

    const baseUrl = `https://${req.headers.host}`;
    const audioUrl = `${baseUrl}/audio.mp3?ts=${Date.now()}`; // ts to avoid Twilio caching weirdness

    const twiml = `<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Play>${escapeXml(audioUrl)}</Play>
</Response>`;

    res.writeHead(200, { 'Content-Type': 'text/xml' });
    res.end(twiml);
    console.log(`[${new Date().toISOString()}] TwiML served <Play> url=${audioUrl}`);
    return;
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Not Found' }));
});

server.listen(PORT, () => {
  console.log(`[${new Date().toISOString()}] ✅ DES server listening on ${PORT}`);
});

async function synthesizeElevenMp3(text) {
  const resp = await fetch(`https://api.elevenlabs.io/v1/text-to-speech/${ELEVEN_VOICE_ID}`, {
    method: 'POST',
    headers: {
      'xi-api-key': ELEVEN_API_KEY,
      'Content-Type': 'application/json',
      Accept: 'audio/mpeg'
    },
    body: JSON.stringify({
      model_id: ELEVEN_MODEL,
      text,
      voice_settings: { stability: 0.5, similarity_boost: 0.8 }
    })
  });

  if (!resp.ok) {
    const errTxt = await resp.text().catch(() => '');
    throw new Error(`ELEVEN_TTS_FAILED ${resp.status}: ${errTxt}`);
  }

  const buf = Buffer.from(await resp.arrayBuffer());
  if (!buf.length) throw new Error('ELEVEN_EMPTY_AUDIO');
  return buf;
}

function escapeXml(s) {
  return String(s)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');
}

